// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INCLUDETEST1_H_
#define FLATBUFFERS_GENERATED_INCLUDETEST1_H_

#include "flatbuffers/flatbuffers.h"

#include "sub/include_test2_generated.h"

struct TableA;
struct TableABuilder;

struct TableA FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TableABuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_B = 4
  };
  const MyGame::OtherNameSpace::TableB *b() const {
    return GetPointer<const MyGame::OtherNameSpace::TableB *>(VT_B);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_B) &&
           verifier.VerifyTable(b()) &&
           verifier.EndTable();
  }
};

struct TableABuilder {
  typedef TableA Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_b(flatbuffers::Offset<MyGame::OtherNameSpace::TableB> b) {
    fbb_.AddOffset(TableA::VT_B, b);
  }
  explicit TableABuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TableA> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TableA>(end);
    return o;
  }
};

inline flatbuffers::Offset<TableA> CreateTableA(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<MyGame::OtherNameSpace::TableB> b = 0) {
  TableABuilder builder_(_fbb);
  builder_.add_b(b);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_INCLUDETEST1_H_
