name: Integration
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build_and_upload_artifact_for_macos_and_linux:
    strategy:
      matrix:
        config:
        - { os: ubuntu-latest, name: 'Linux'}
        - { os: macos-latest, name: 'MacOs'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin 'refs/tags/*:refs/tags/*'
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Configure cmake
        run: |
          mkdir cmake-build-release && cd cmake-build-release && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      - name: Build bufc
        run: |
          make bufc
        working-directory: cmake-build-release
      - name: Update Nuget Source
        run: |
          dotnet nuget update source GitHub-StirlingLabs --source https://nuget.pkg.github.com/StirlingLabs/index.json --username ${{github.repository_owner}}  --password ${{github.token}} --store-password-in-clear-text
        working-directory: net
      - name: Build BigBuffers Net Projects
        run: |
          dotnet build BigBuffers.sln -c Release
        working-directory: net
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }} bufc Binary
          path: cmake-build-release/bufc
  build_and_upload_artifact_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin 'refs/tags/*:refs/tags/*'
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Configure cmake
        run: |
          mkdir cmake-build-release && cd cmake-build-release && cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
      - name: Build bufc
        run: |
          msbuild.exe bufc.vcxproj /p:Configuration=Release /p:Platform=x64
        working-directory: cmake-build-release
      - name: Update Nuget Source
        run: |
          dotnet nuget update source GitHub-StirlingLabs --source https://nuget.pkg.github.com/StirlingLabs/index.json --username ${{github.repository_owner}}  --password ${{github.token}} --store-password-in-clear-text
        working-directory: net
      - name: Build Net Project
        run: |
          dotnet build -c Release
        working-directory: net
      - name: Run Net Project Test
        run: |
          dotnet test --no-build -c Release --logger GitHubActions
        working-directory: net
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Win64 bufc Binary
          path: |
            ${{ github.workspace }}\cmake-build-release\*.exe
      - name: Upload nupkg files
        uses: actions/upload-artifact@v2
        with:
          name: Nuget files
          path: |
            ${{ github.workspace }}\net\artifacts\*.nupkg