name: Integration
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build_and_upload_artifact_for_macos_and_linux:
    strategy:
      matrix:
        config:
        - { os: ubuntu-latest, name: 'Linux'}
        - { os: macos-latest, name: 'MacOs'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure cmake
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .
      - name: Build bufc
        run: |
          make bufc
      - name: upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config.name }} Bufc Binary
          path: bufc
  build_and_upload_artifact_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Configure cmake
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Build Bufc
        run: |
          msbuild.exe bufc.vcxproj /p:Configuration=Release /p:Platform=x64
      - name: Create Cmake Release Directory And Copy bufc
        shell: pwsh
        run: |
          mkdir cmake-build-release && cp Release\bufc.exe cmake-build-release\bufc.exe
      - name: Create Sln file and add project sln
        run: |
          dotnet new sln -n BigBuffers && dotnet sln add $(find . -name "*.csproj")
        shell: bash
        working-directory: net
      - name: Update Nuget Source
        run: |
          dotnet nuget update source GitHub-StirlingLabs --source https://nuget.pkg.github.com/StirlingLabs/index.json --username ${{github.repository_owner}}  --password ${{github.token}} --store-password-in-clear-text
        working-directory: net
      - name: Build Net Project
        run: |
          dotnet build -c Release
        working-directory: net
      - name: Run Net Project Test
        run: |
          dotnet test --no-build -c Release --logger GitHubActions
        working-directory: net
      - name: Save coverage to storage branch
        uses: StirlingLabs/BranchStorageAction@v21.07.3
        with:
          comment: |
            Coverage for ${{github.ref}}
            Action: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            Commit: https://github.com/${{github.repository}}/commit/${{github.sha}}
          storage-branch: coverage
          src: coverage
          dst: coverage
          prune: true
      - name: upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Win64 Bufc Binary
          path: |
            Release\bufc.exe
            net/articafts/*.nupkg